version: '3.8'

services:
  bumper-bot:
    build: .
    image: 0xgio/bumper-bot:latest
    ports:
      - "8080:8080"
    environment:
      - DECRYPT_PASSWORD=${DECRYPT_PASSWORD}
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BOT_PUBLIC_KEY=${BOT_PUBLIC_KEY}
      - BOT_SECRET_KEY=${BOT_SECRET_KEY}
      - PRIORITY_FEE=0.${PRIORITY_FEE}
      - RPC=${RPC}
      - RPC_TX=${RPC_TX}
